### ISSUE TITLE
page blank page in my domaine

### ISSUE THREAD

**Issue by hatemgh123** [Salmen2/FaucetHub-Faucet#10]
your code working in my local host but in my domaine she dont working( page blank page ) what's the problme ??

**Comment by dezzer7** [comment]
did you solve it ?

**Comment by dezzer7** [comment]
having the same problem

**Comment by hatemgh123** [comment]
not yet  i'm trying to search this solution since three day  ;)

**Comment by Salmen2** [comment]
Does the problem appear on the index.php page?

**Comment by rykerdz** [comment]
We dont see anything , just a blank page

**Comment by Salmen2** [comment]
May I know which PHP version you are running?

**Comment by rykerdz** [comment]
How can i know ?

**Comment by Salmen2** [comment]
Nevermind. Just amended a thing, please download the script from here (https://github.com/Salmen2/FaucetHub-Faucet/archive/master.zip) and replace the current index.php with the index.php in the zip file.

**Comment by Salmen2** [comment]
Additionally, you have to make sure you are not running PHP 7.0

**Comment by hatemgh123** [comment]
thx Salmen2  i'm was using in  php 7.0 :)

**Comment by aihmgmal** [comment]
مرحبا  لم  قتح  هناك خطأ بعد الضافة  داتا بست  لم  يفتح ؟؟؟؟

**Comment by 5iwek** [comment]
The issue still exists. The page is blank even though I use PHP 5.6.
