### ISSUE TITLE
Do Not Try on PHP7.0

### ISSUE THREAD

**Issue by Stjowa** [Salmen2/FaucetHub-Faucet#11]
I know the description said this but I tried anyways.

If anyone knows how to make this work though let me know! Interested to poke with it on PHP7.0

I have added in some echos and it appears it does work but not with the templating.

**Comment by anjilite7** [comment]
I use google reCaptcha. It says "Captcha is wrong." even if i solved captcha right. Whats wrong? Help if you can.

**Comment by Salmen2** [comment]
As far as I know, PHP 5.6 or PHP 7.0 suggest alternative methods on how to use the script in the newest PHP versions.
