### ISSUE TITLE
Unknown

### ISSUE THREAD

**Issue by Kimmn04** [Salmen2/FaucetHub-Faucet#14]
I configured the setting and Import SQL, but after trying to input my btc address on index.php the page didn't redirect  me to the captcha  and claim page.

Here is my test page : http://bitcoingreen.000webhostapp.com/index.php

**Comment by Salmen2** [comment]
Hello. Have you tried to use another web hoster? This kind of issue seems to appear only on 000webhost.

**Comment by 5iwek** [comment]
Hi, I have the same issue with OVH. Is there any solution?
