### ISSUE TITLE
500 error when claiming

### ISSUE THREAD

**Issue by danielwang404** [Salmen2/FaucetHub-Faucet#3]
I've switched to a LAMP stack with PHP version 5.5.9. php -v shows: 
PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct  3 2016 13:00:37)

The main page loads fine, it's just when someone clicks claim that it shows the 500. Apache2 error logs show nothing. I turned on error reporting in the php files and its just a blank page after that.

Files haven't been changed at all, I just uploaded, imported sql.sql with: mysql -u root -p (dbname) < sql.sql

**Comment by danielwang404** [comment]
Ubuntu 14.04 with LEMP works for claiming, still testing other things.

**Comment by danielwang404** [comment]
Thinking that https doesn't work,  server with just http works fine, but when I use https it does not. any reasoning for this?

**Comment by Salmen2** [comment]
Please enable error_reporting in the PHP configuration file.

**Comment by danielwang404** [comment]
Yes i have, in the php.ini one right? blank screen

**Comment by Salmen2** [comment]
If you've enabled error_reporting in php.ini then you need to change in core.php the code:
`error_reporting(0);`
to
`error_reporting(E_ALL);`

After that, it shall works

**Comment by LcclTm** [comment]
Hi, one question. I Test your script and show connection error when i go to withdraw money. What should this be? Thanks for your support. Screenshot ->
![issues e](https://cloud.githubusercontent.com/assets/25607424/22685727/d3a78168-ecf7-11e6-8c93-a9ee0de42532.png)

My API Key is placed where it goes, and still gives me this error. Could you help me please?

**Comment by Salmen2** [comment]
This problem is from FaucetHub's site since their API returns the error 504.
