### ISSUE TITLE
My API Key is placed where it goes

### ISSUE THREAD

**Issue by LcclTm** [Salmen2/FaucetHub-Faucet#4]
Hi, one question. I Test your script and show connection error when i go to withdraw money. What should this be? Thanks for your support. Screenshot ->
![issues e](https://cloud.githubusercontent.com/assets/25607424/22719306/39cd5ff2-ed7b-11e6-9e22-4bd02f1540c5.png)
My API Key is placed where it goes, and still gives me this error. Could you help me please?

**Comment by RickBakkr** [comment]
You probably try to connect with Faucethub from your resident connection? When I tried doing any call to the FaucetHub API from localhost, the request failed with the same error. Anyway, it throws this error in when PHP is unable to make a API call.

**Comment by Salmen2** [comment]
According to their API, there is a connection error to FaucetHub API. That means the script gets an empty response from the API. You shall check whether FH's IP is blacklisted by server. You may also try to call the FaucetHub API using the command line of the server.
