### ISSUE TITLE
PHP Warning:  session_start()

### ISSUE THREAD

**Issue by infotheconomicsofbitcoin** [Salmen2/FaucetHub-Faucet#5]
PHP Warning:  session_start(): open(/tmp/sess_3a5sqdd8eu28oho0h91s1ts805, O_RDWR) failed: No such file or directory (2) in /home/thecmnos/public_html/includes/core.php on line 2

**Comment by Salmen2** [comment]
It seems that is a kind of the server error. You may need to contact the server administrator.
