### ISSUE TITLE
Referral Link

### ISSUE THREAD

**Issue by danielwang404** [Salmen2/FaucetHub-Faucet#7]
How would I go rewriting the URL for referral addresses? 

I mean instead of 

thebtcfaucet.com/?ref="id of user"

I want it to be

thebtcfaucet.com/?r="bitcoin address"

The closest thing I found for this was changing this code:

	public function getRefLink() {
		$siteUrl = $_SERVER["SERVER_NAME"];
		return 'http://' . $siteUrl . '/index.php?ref=' . $this->address;
	}

and updating the SQL database?
Thanks for your help Salmen!

**Comment by Salmen2** [comment]
Replace
```
if(!$_COOKIE['refer']){
	if($_GET['ref'] != ""){
		$refer = $mysqli->real_escape_string($_GET['ref']);
		setcookie("refer", $refer,time()+(3600*24));
	}
}
```
to
```
if(!$_COOKIE['refer']){
	if($_GET['r'] != ""){
		$btcAddyRef = $mysqli->real_escape_string($_GET['r']);
		$IDaddy = $mysqli->query("SELECT id FROM faucet_user_list WHERE address = '$btcAddyRef'");
		if($IDaddy->num_rows == 1){
			$IDaddy = $IDaddy->fetch_assoc();
			setcookie("refer", $IDaddy['id'],time()+(3600*24));
		}
	}
}
```
after that it shall work.
