### ISSUE TITLE
Error 500 - PHP

### ISSUE THREAD

**Issue by thetechnoman1** [Salmen2/FaucetHub-Faucet#8]
I get an error 500 when claiming and this appears in the log.. any ideas?
`[Thu Mar 23 23:34:23.473254 2017] [:error] [pid 28499] [client 31.48.69.207:25279] PHP Notice:  Undefined index: address in /var/www/html/includes/session.php on line 2, referer: http://freebtcoin.tk/admin.php
[Thu Mar 23 23:34:23.474578 2017] [:error] [pid 28499] [client 31.48.69.207:25279] PHP Deprecated:  preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /var/www/html/includes/template.class.php on line 95, referer: http://freebtcoin.tk/admin.php
[Thu Mar 23 23:34:23.477678 2017] [:error] [pid 28499] [client 31.48.69.207:25279] PHP Notice:  Undefined variable: navBarLinks in /var/www/html/includes/template.settings.php on line 31, referer: http://freebtcoin.tk/admin.php
[Thu Mar 23 23:34:23.485824 2017] [:error] [pid 28499] [client 31.48.69.207:25279] PHP Notice:  Undefined index: refer in /var/www/html/includes/core.php on line 11, referer: http://freebtcoin.tk/admin.php
[Thu Mar 23 23:34:23.485849 2017] [:error] [pid 28499] [client 31.48.69.207:25279] PHP Notice:  Undefined index: ref in /var/www/html/includes/core.php on line 12, referer: http://freebtcoin.tk/admin.php
[Thu Mar 23 23:34:23.486766 2017] [:error] [pid 28499] [client 31.48.69.207:25279] PHP Notice:  Undefined index: token in /var/www/html/includes/core.php on line 43, referer: http://freebtcoin.tk/admin.php
[Thu Mar 23 23:34:23.487023 2017] [:error] [pid 28499] [client 31.48.69.207:25279] PHP Notice:  Undefined variable: user in /var/www/html/index.php on line 6, referer: http://freebtcoin.tk/admin.php
[Thu Mar 23 23:34:23.487262 2017] [:error] [pid 28499] [client 31.48.69.207:25279] PHP Notice:  Undefined variable: alertForm in /var/www/html/index.php on line 211, referer: http://freebtcoin.tk/admin.php
[Thu Mar 23 23:34:23.487277 2017] [:error] [pid 28499] [client 31.48.69.207:25279] PHP Notice:  Undefined variable: Address in /var/www/html/index.php on line 213, referer: http://freebtcoin.tk/admin.php
[Thu Mar 23 23:34:26.887460 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined index: address in /var/www/html/includes/session.php on line 2, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:26.887663 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Deprecated:  preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /var/www/html/includes/template.class.php on line 95, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:26.888326 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined variable: navBarLinks in /var/www/html/includes/template.settings.php on line 31, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:26.888443 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined index: refer in /var/www/html/includes/core.php on line 11, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:26.888452 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined index: ref in /var/www/html/includes/core.php on line 12, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:26.888563 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined variable: user in /var/www/html/index.php on line 6, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:26.888929 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined index: refer in /var/www/html/index.php on line 168, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:26.925193 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Deprecated:  preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /var/www/html/includes/template.class.php on line 95, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:26.925802 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined variable: navBarLinks in /var/www/html/includes/template.settings.php on line 31, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:26.925843 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined index: refer in /var/www/html/includes/core.php on line 11, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:26.925849 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined index: ref in /var/www/html/includes/core.php on line 12, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:26.926379 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined index: c in /var/www/html/index.php on line 41, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:29.119810 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Deprecated:  preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /var/www/html/includes/template.class.php on line 95, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:29.120657 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined variable: navBarLinks in /var/www/html/includes/template.settings.php on line 31, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:29.120729 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined index: refer in /var/www/html/includes/core.php on line 11, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:29.120738 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined index: ref in /var/www/html/includes/core.php on line 12, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:29.120947 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined variable: timer in /var/www/html/verify.php on line 7, referer: http://freebtcoin.tk/index.php
[Thu Mar 23 23:34:32.055877 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Deprecated:  preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /var/www/html/includes/template.class.php on line 95, referer: http://freebtcoin.tk/verify.php
[Thu Mar 23 23:34:32.056441 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined variable: navBarLinks in /var/www/html/includes/template.settings.php on line 31, referer: http://freebtcoin.tk/verify.php
[Thu Mar 23 23:34:32.056515 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined index: refer in /var/www/html/includes/core.php on line 11, referer: http://freebtcoin.tk/verify.php
[Thu Mar 23 23:34:32.056523 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Notice:  Undefined index: ref in /var/www/html/includes/core.php on line 12, referer: http://freebtcoin.tk/verify.php
[Thu Mar 23 23:34:32.252193 2017] [:error] [pid 28501] [client 31.48.69.207:26437] PHP Fatal error:  Call to undefined function curl_init() in /var/www/html/includes/functions.php on line 33, referer: http://freebtcoin.tk/verify.php
RAW Paste Data
`

**Comment by danielwang404** [comment]
What version of PHP are you running, OS, etc. 

PHP 7.0 will not work,

You must use PHP 5.6 or lower, because the template system is deprecated.

**Comment by Salmen2** [comment]
You need to install curl on your server. Command "sudo apt-get install php5-curl"

**Comment by thetechnoman1** [comment]
It worked! Thanks
